server:
  port: 8080
  
spring:
  application:
    name: zuul

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/ 



zuul: 
  ignoredServices: '*'
  routes:
    userService:
      path: /userService/**
      serviceId: userService
  prefix: /api    
 